### ISSUE TITLE
NXXX parameter doesn't seem to be optional in set() method

### ISSUE THREAD

**Issue by bmvzane** [xetorthio/jedis#1800]
### Expected behavior

nxxx = null or ""
expx = "PX"
ttl = 5000;

jedis.set(key, value, nxxx, expx, ttl);

Should write to redis successfully since NX|XX is optional in redis SET .
Or maybe a method signature without nxxx parameter.

### Actual behavior

nxxx = null
Exception
! redis.clients.jedis.exceptions.JedisDataException: value sent to redis cannot be null
! at redis.clients.util.SafeEncoder.encode(SafeEncoder.java:28)
! at redis.clients.jedis.Client.set(Client.java:52)
! at redis.clients.jedis.Jedis.set(Jedis.java:138)

nxxx = ""
Exception
! redis.clients.jedis.exceptions.JedisDataException: ERR syntax error
! at redis.clients.jedis.Protocol.processError(Protocol.java:127)
! at redis.clients.jedis.Protocol.process(Protocol.java:161)
! at redis.clients.jedis.Protocol.read(Protocol.java:215)
! at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
! at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:239)
! at redis.clients.jedis.Jedis.set(Jedis.java:139)

### Steps to reproduce:

nxxx = null or ""
expx = "PX"
ttl = 5000;

jedis.set(key, value, nxxx, expx, ttl);

#### Jedis version:
2.9.0

#### Redis version:
4.0.2

#### Java version:
1.8.0_40

**Comment by sazzad16** [comment]
Already resolved by #1433

**Comment by fokkoru** [comment]
It is still an issue for the pipeline set method, am I right?

**Comment by sazzad16** [comment]
@fokkoru yes.
